// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnicasaProveedoresWeb.Models;

#nullable disable

namespace UnicasaProveedoresAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_EMPLOYEE", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"));

                    b.Property<string>("codigo_proveedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<string>("employee_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("id_created_by")
                        .HasColumnType("int");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.HasKey("employee_id");

                    b.HasIndex("id_created_by");

                    b.HasIndex("id_user");

                    b.ToTable("UWP_EMPLOYEE", (string)null);
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_PERMISSION", b =>
                {
                    b.Property<int>("permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permission_id"));

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_created_by")
                        .HasColumnType("int");

                    b.Property<string>("permission_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("permission_id");

                    b.HasIndex("id_created_by");

                    b.ToTable("UWP_PERMISSION", (string)null);
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_PROVEEDOR", b =>
                {
                    b.Property<int>("proveedor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proveedor_id"));

                    b.Property<string>("codigo_proveedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_created_by")
                        .HasColumnType("int");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<string>("proveedor_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("proveedor_id");

                    b.HasIndex("id_created_by");

                    b.HasIndex("id_user");

                    b.ToTable("UWP_PROVEEDOR", (string)null);
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_ROL", b =>
                {
                    b.Property<int>("rol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rol_id"));

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<string>("rol_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("rol_id");

                    b.ToTable("UWP_ROL", (string)null);
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_ROL_PERMISSION", b =>
                {
                    b.Property<int>("rol_permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rol_permission_id"));

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_created_by")
                        .HasColumnType("int");

                    b.Property<int>("id_permission")
                        .HasColumnType("int");

                    b.Property<int>("id_rol")
                        .HasColumnType("int");

                    b.HasKey("rol_permission_id");

                    b.HasIndex("id_created_by");

                    b.HasIndex("id_permission");

                    b.HasIndex("id_rol");

                    b.ToTable("UWP_ROL_PERMISSION", (string)null);
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_USER", b =>
                {
                    b.Property<int>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usuario_id"));

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_created_by")
                        .HasColumnType("int");

                    b.Property<int>("id_rol")
                        .HasColumnType("int");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("user_status")
                        .HasColumnType("bit");

                    b.Property<string>("user_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user_username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuario_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("usuario_id");

                    b.HasIndex("id_created_by");

                    b.HasIndex("id_rol");

                    b.ToTable("UWP_USER", (string)null);
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_EMPLOYEE", b =>
                {
                    b.HasOne("UnicasaProveedoresWeb.Models.UWP_USER", "created_by")
                        .WithMany()
                        .HasForeignKey("id_created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnicasaProveedoresWeb.Models.UWP_USER", "user")
                        .WithMany("empleado")
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("created_by");

                    b.Navigation("user");
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_PERMISSION", b =>
                {
                    b.HasOne("UnicasaProveedoresWeb.Models.UWP_USER", "created_by")
                        .WithMany()
                        .HasForeignKey("id_created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("created_by");
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_PROVEEDOR", b =>
                {
                    b.HasOne("UnicasaProveedoresWeb.Models.UWP_USER", "created_by")
                        .WithMany()
                        .HasForeignKey("id_created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnicasaProveedoresWeb.Models.UWP_USER", "user")
                        .WithMany("proveedor")
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("created_by");

                    b.Navigation("user");
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_ROL_PERMISSION", b =>
                {
                    b.HasOne("UnicasaProveedoresWeb.Models.UWP_USER", "created_by")
                        .WithMany()
                        .HasForeignKey("id_created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnicasaProveedoresWeb.Models.UWP_PERMISSION", "permission")
                        .WithMany("rol_permission")
                        .HasForeignKey("id_permission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnicasaProveedoresWeb.Models.UWP_ROL", "rol")
                        .WithMany("rol_permission")
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("created_by");

                    b.Navigation("permission");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_USER", b =>
                {
                    b.HasOne("UnicasaProveedoresWeb.Models.UWP_USER", "created_by")
                        .WithMany()
                        .HasForeignKey("id_created_by")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UnicasaProveedoresWeb.Models.UWP_ROL", "rol")
                        .WithMany()
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("created_by");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_PERMISSION", b =>
                {
                    b.Navigation("rol_permission");
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_ROL", b =>
                {
                    b.Navigation("rol_permission");
                });

            modelBuilder.Entity("UnicasaProveedoresWeb.Models.UWP_USER", b =>
                {
                    b.Navigation("empleado");

                    b.Navigation("proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
